Team91LMS/LMS_handout/LMS/Models/LMSModels/Assignments.cs
using System;
using System.Collections.Generic;

namespace LMS.Models.LMSModels
{
    public partial class Assignments
    {
        public Assignments()
        {
            Submissions = new HashSet<Submissions>();
        }

        public uint Aid { get; set; }
        public uint Acid { get; set; }
        public string AssignmentName { get; set; }
        public DateTime DueDate { get; set; }
        public string AssignmentContents { get; set; }
        public uint MaxPointValue { get; set; }

        public virtual AssignmentCategories Ac { get; set; }
        public virtual ICollection<Submissions> Submissions { get; set; }
    }
}

Team91LMS/LMS_handout/LMS/Models/LMSModels/Professors.cs
using System;
using System.Collections.Generic;

namespace LMS.Models.LMSModels
{
    public partial class Professors
    {
        public Professors()
        {
            Classes = new HashSet<Classes>();
        }

        public string UId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime Dob { get; set; }
        public string SubjectAbv { get; set; }

        public virtual Departments SubjectAbvNavigation { get; set; }
        public virtual ICollection<Classes> Classes { get; set; }
    }
}

Team91LMS/LMS_handout/LMS/Models/LMSModels/Students.cs
using System;
using System.Collections.Generic;

namespace LMS.Models.LMSModels
{
    public partial class Students
    {
        public Students()
        {
            EnrolledIn = new HashSet<EnrolledIn>();
            Submissions = new HashSet<Submissions>();
        }

        public string UId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime Dob { get; set; }
        public string SubjectAbv { get; set; }

        public virtual Departments SubjectAbvNavigation { get; set; }
        public virtual ICollection<EnrolledIn> EnrolledIn { get; set; }
        public virtual ICollection<Submissions> Submissions { get; set; }
    }
}

Team91LMS/LMS_handout/LMS/Models/LMSModels/Submissions.cs
using System;
using System.Collections.Generic;

namespace LMS.Models.LMSModels
{
    public partial class Submissions
    {
        public uint Aid { get; set; }
        public string UId { get; set; }
        public DateTime SubmissionTime { get; set; }
        public string SubmissionContents { get; set; }
        public uint SubmissionScore { get; set; }

        public virtual Assignments A { get; set; }
        public virtual Students U { get; set; }
    }
}

Team91LMS/LMS_handout/LMS/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LMS.Models.LMSModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LMS.Controllers
{
  public class CommonController : Controller
  {

    /*******Begin code to modify********/

    // TODO: Uncomment and change 'X' after you have scaffoled

    
    protected Team91LMSContext db;

    public CommonController()
    {
      db = new Team91LMSContext();
    }
    

    /*
     * WARNING: This is the quick and easy way to make the controller
     *          use a different LibraryContext - good enough for our purposes.
     *          The "right" way is through Dependency Injection via the constructor 
     *          (look this up if interested).
    */

    // TODO: Uncomment and change 'X' after you have scaffoled
    
    public void UseLMSContext(Team91LMSContext ctx)
    {
      db = ctx;
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing)
      {
        db.Dispose();
      }
      base.Dispose(disposing);
    }
    



    /// <summary>
    /// Retreive a JSON array of all departments from the database.
    /// Each object in the array should have a field called "name" and "subject",
    /// where "name" is the department name and "subject" is the subject abbreviation.
    /// </summary>
    /// <returns>The JSON array</returns>
    public IActionResult GetDepartments()
    {
            using (Team91LMSContext db = new Team91LMSContext())
            {
                var query = from p in db.Departments
                            select new {name = p.DepartmentName, subject = p.SubjectAbv };
                return Json(query.ToArray());
            }
                // TODO: Do not return this hard-coded array.
                //return Json(new[] { new { name = "None", subject = "NONE" } });
    }



    /// <summary>
    /// Returns a JSON array representing the course catalog.
    /// Each object in the array should have the following fields:
    /// "subject": The subject abbreviation, (e.g. "CS")
    /// "dname": The department name, as in "Computer Science"
    /// "courses": An array of JSON objects representing the courses in the department.
    ///            Each field in this inner-array should have the following fields:
    ///            "number": The course number (e.g. 5530)
    ///            "cname": The course name (e.g. "Database Systems")
    /// </summary>
    /// <returns>The JSON array</returns>
    public IActionResult GetCatalog()
    {
            using (Team91LMSContext db = new Team91LMSContext())
            {
                var query = from p in db.Departments
                            select new { subject = p.SubjectAbv, dname = p.DepartmentName, courses = from i in db.Courses
                                                                                                     where i.SubjectAbv == p.SubjectAbv
                                                                                                     select new {number = i.CourseNumber, cname = i.CourseName } };
                return Json(query.ToArray());
            }
            //return Json(null);
    }

    /// <summary>
    /// Returns a JSON array of all class offerings of a specific course.
    /// Each object in the array should have the following fields:
    /// "season": the season part of the semester, such as "Fall"
    /// "year": the year part of the semester
    /// "location": the location of the class
    /// "start": the start time in format "hh:mm:ss"
    /// "end": the end time in format "hh:mm:ss"
    /// "fname": the first name of the professor
    /// "lname": the last name of the professor
    /// </summary>
    /// <param name="subject">The subject abbreviation, as in "CS"</param>
    /// <param name="number">The course number, as in 5530</param>
    /// <returns>The JSON array</returns>
    public IActionResult GetClassOfferings(string subject, int number)
    {
            using (Team91LMSContext db = new Team91LMSContext())
            {
                var query = from p in db.Courses
                            join j1 in db.Classes
                            on p.CourseId equals j1.CourseId
                            join j2 in db.Professors
                            on j1.UId equals j2.UId
                            where p.CourseNumber == number.ToString() && p.SubjectAbv == subject
                            select new { season = j1.SemesterSeason, year = j1.SemesterYear, location = j1.Location, start = j1.StartTime, end = j1.EndTime, fname = j2.FirstName, lname = j2.LastName };
                return Json(query.ToArray());
            }
            //return Json(null);
    }

    /// <summary>
    /// This method does NOT return JSON. It returns plain text (containing html).
    /// Use "return Content(...)" to return plain text.
    /// Returns the contents of an assignment.
    /// </summary>
    /// <param name="subject">The course subject abbreviation</param>
    /// <param name="num">The course number</param>
    /// <param name="season">The season part of the semester for the class the assignment belongs to</param>
    /// <param name="year">The year part of the semester for the class the assignment belongs to</param>
    /// <param name="category">The name of the assignment category in the class</param>
    /// <param name="asgname">The name of the assignment in the category</param>
    /// <returns>The assignment contents</returns>
    public IActionResult GetAssignmentContents(string subject, int num, string season, int year, string category, string asgname)
    {
            using (Team91LMSContext db = new Team91LMSContext())
            {
                var query = from p in db.Courses
                            join j1 in db.Classes
                            on p.CourseId equals j1.CourseId
                            where j1.SemesterSeason == season && j1.SemesterYear == year && p.SubjectAbv == subject && p.CourseNumber == num.ToString()
                            join j2 in db.AssignmentCategories
                            on j1.ClassId equals j2.ClassId
                            where j2.AssignmentCategoryName == category
                            join j3 in db.Assignments
                            on j2.Acid equals j3.Acid
                            where j3.AssignmentName == asgname
                            select j3.AssignmentContents;
                return Content(query.FirstOrDefault());
            }
                    //return Content("");
    }


    /// <summary>
    /// This method does NOT return JSON. It returns plain text (containing html).
    /// Use "return Content(...)" to return plain text.
    /// Returns the contents of an assignment submission.
    /// Returns the empty string ("") if there is no submission.
    /// </summary>
    /// <param name="subject">The course subject abbreviation</param>
    /// <param name="num">The course number</param>
    /// <param name="season">The season part of the semester for the class the assignment belongs to</param>
    /// <param name="year">The year part of the semester for the class the assignment belongs to</param>
    /// <param name="category">The name of the assignment category in the class</param>
    /// <param name="asgname">The name of the assignment in the category</param>
    /// <param name="uid">The uid of the student who submitted it</param>
    /// <returns>The submission text</returns>
    public IActionResult GetSubmissionText(string subject, int num, string season, int year, string category, string asgname, string uid)
    {
            using (Team91LMSContext db = new Team91LMSContext())
            {
                var query = from p in db.Courses
                            join j1 in db.Classes
                            on p.CourseId equals j1.CourseId
                            where j1.SemesterSeason == season && j1.SemesterYear == year && p.SubjectAbv == subject && p.CourseNumber == num.ToString()
                            join j2 in db.AssignmentCategories
                            on j1.ClassId equals j2.ClassId
                            where j2.AssignmentCategoryName == category
                            join j3 in db.Assignments
                            on j2.Acid equals j3.Acid
                            where j3.AssignmentName == asgname
                            join j4 in db.Submissions
                            on j3.Aid equals j4.Aid
                            where j4.UId == uid
                            select j4.SubmissionContents;
                return Content(query.FirstOrDefault());
            }
            //return Content("");
    }


    /// <summary>
    /// Gets information about a user as a single JSON object.
    /// The object should have the following fields:
    /// "fname": the user's first name
    /// "lname": the user's last name
    /// "uid": the user's uid
    /// "department": (professors and students only) the name (such as "Computer Science") of the department for the user. 
    ///               If the user is a Professor, this is the department they work in.
    ///               If the user is a Student, this is the department they major in.    
    ///               If the user is an Administrator, this field is not present in the returned JSON
    /// </summary>
    /// <param name="uid">The ID of the user</param>
    /// <returns>
    /// The user JSON object 
    /// or an object containing {success: false} if the user doesn't exist
    /// </returns>
    public IActionResult GetUser(string uid)
    {
            using (Team91LMSContext db = new Team91LMSContext())
            {
                //students
                var query = from p in db.Students
                            where p.UId.Equals(uid)
                            join c in db.Departments

Team91LMS/LMS_handout/LMS/Views/Professor/Assignment.cshtml
@{
    ViewData["Title"] = "Assignment";
    Layout = "~/Views/Shared/ProfessorLayout.cshtml";
}


<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body {
      font-family: "Lato", sans-serif;
    }

    .sidenav {
      /*width: 130px;
      height: 210px;
      position: fixed;
      z-index: 1;
      top: 80px;
      left: 10px;*/
      width: 130px;
      height: 210px;
      position: fixed;
      left: 0;
      right: 0;
      /*margin-left: auto;
      margin-right: auto;*/
      z-index: 1;
      top: 50px;
      background: #eee;
      overflow-x: hidden;
      padding: 8px 0;
    }

      .sidenav a {
        padding: 6px 8px 6px 16px;
        text-decoration: none;
        font-size: 18px;
        color: #2196F3;
        display: block;
      }

        .sidenav a:hover {
          color: #064579;
        }

    .main {
      margin-left: 140px;
      min-height: 200px;
      padding: 0px 10px;
    }
  </style>
</head>
<body>

  <div class="sidenav">
    <a href='/Professor/Class?subject=@ViewData["subject"]&num=@ViewData["num"]&season=@ViewData["season"]&year=@ViewData["year"]'>Assignments</a>
    <a href='/Professor/Students?subject=@ViewData["subject"]&num=@ViewData["num"]&season=@ViewData["season"]&year=@ViewData["year"]'>Students</a>
    <a href='/Professor/Categories?subject=@ViewData["subject"]&num=@ViewData["num"]&season=@ViewData["season"]&year=@ViewData["year"]'>Assignment Categories</a>
  </div>


  <div class="main">
    <h4 id="asgname">Assignment</h4>
    <div id="asgcontents"></div>

  </div>
</body>
</html>





@section Scripts
  {
  <script type="text/javascript">

    LoadData();

    function LoadData() {

      asgname.innerText = '@ViewData["aname"]';

      $.ajax({
        type: 'POST',
        url: '@Url.Action("GetAssignmentContents", "Common")',
        dataType: 'text',
        data: {
          subject: '@ViewData["subject"]',
          num: Number('@ViewData["num"]'),
          season: '@ViewData["season"]',
          year: Number('@ViewData["year"]'),
          category: '@ViewData["cat"]',
          asgname: '@ViewData["aname"]'},
        success: function (data, status) {
          //alert(data);

          var contentsdiv = document.getElementById("asgcontents");
          contentsdiv.innerHTML = data;
          
        },
          error: function (ex) {
              alert("GetAssignmentContents controller did not return successfully");
        }
        });


    }

  </script>

}

Team91LMS/LMS_handout/LMS/Views/Professor/CatAssignments.cshtml
@{
  ViewData["Title"] = "CatAssignments";
  Layout = "~/Views/Shared/ProfessorLayout.cshtml";
}

<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body {
      font-family: "Lato", sans-serif;
    }

    .sidenav {
      /*width: 130px;
      height: 210px;
      position: fixed;
      z-index: 1;
      top: 80px;
      left: 10px;*/
      width: 130px;
      height: 210px;
      position: fixed;
      left: 0;
      right: 0;
      /*margin-left: auto;
      margin-right: auto;*/
      z-index: 1;
      top: 50px;
      background: #eee;
      overflow-x: hidden;
      padding: 8px 0;
    }

      .sidenav a {
        padding: 6px 8px 6px 16px;
        text-decoration: none;
        font-size: 18px;
        color: #2196F3;
        display: block;
      }

        .sidenav a:hover {
          color: #064579;
        }

    .main {
      margin-left: 140px;
      min-height: 200px;
      padding: 0px 10px;
    }
  </style>
</head>
<body>

  <div class="sidenav">
    <a href='/Professor/Class?subject=@ViewData["subject"]&num=@ViewData["num"]&season=@ViewData["season"]&year=@ViewData["year"]'>Assignments</a>
    <a href='/Professor/Students?subject=@ViewData["subject"]&num=@ViewData["num"]&season=@ViewData["season"]&year=@ViewData["year"]'>Students</a>
    <a href='/Professor/Categories?subject=@ViewData["subject"]&num=@ViewData["num"]&season=@ViewData["season"]&year=@ViewData["year"]'>Assignment Categories</a>
  </div>


  <div class="main">
    <h4 id="classname">Class</h4>

    <div id="departmentDiv" class="col-md-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Assignments in '@ViewData["cat"]'</h3>
        </div>
        <div class="panel-body">
          <table id="tblAssignments" class="table table-bordered table-striped table-responsive table-hover">
            <thead>
              <tr>
                <th align="left" class="productth">Name</th>
                <th align="left" class="productth">Due</th>
                <th align="left" class="productth">Submissions</th>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">New Assignment</h3>
        </div>
        <div class="panel-body">
          <div class="clearfix"></div>
          <div class="form-group col-md-5">
            <label>Name</label>
            <input type="text" name="AsgName" id="AsgName" class="form-control" placeholder="Enter assignment name" required="" />
          </div>
          <div class="form-group col-md-5">
            <label>Points</label>
            <input type="text" name="AsgPoints" id="AsgPoints" class="form-control" placeholder="Enter max points" required="" />
          </div>
          <br />
          <div class="form-group col-md-5">
            <label>Due</label>
            <input type="datetime-local" name="AsgDue" id="AsgDue" value="2018-01-01T23:59:59">
          </div>
          <br />
          <div class="form-group col-md-3">
            <textarea rows="4" cols="50" name="AsgContents" id="AsgContents">Enter contents here</textarea>
          </div>

          <div class="form-group col-md-5">
            <div style="float: right; display:inline-block;">
              <input class="btn btn-primary" name="submitButton" id="btnSave" value="Add" type="button" onclick="AddAssignment()">
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</body>
</html>





@section Scripts
  {
  <script type="text/javascript">

    LoadData();

    function PopulateTable(tbl, offerings) {
      var newBody = document.createElement("tbody");

      $.each(offerings, function (i, item) {
        var tr = document.createElement("tr");

        
        var td = document.createElement("td");
        var a = document.createElement("a");
        a.setAttribute("href", "/Professor/Assignment/?subject=" + '@ViewData["subject"]' + "&num=" + '@ViewData["num"]' + "&season=" + '@ViewData["season"]' + "&year=" + '@ViewData["year"]' + "&cat=" + '@ViewData["cat"]' + "&aname=" + item.aname);
        a.appendChild(document.createTextNode(item.aname));
        td.appendChild(a);
        tr.appendChild(td);

        var td = document.createElement("td");
        td.appendChild(document.createTextNode(item.due));
        tr.appendChild(td);

        var td = document.createElement("td");
        td.appendChild(document.createTextNode(item.submissions));
        tr.appendChild(td);

        newBody.appendChild(tr);
      });

      tbl.appendChild(newBody);


    }

    function AddAssignment() {

      var asgName = $("#AsgName").val();
      var asgPoints = Number($("#AsgPoints").val());
      var asgContents = $("#AsgContents").val();
      var asgDue = document.getElementById("AsgDue").value;

      $.ajax({
        type: 'POST',
        url: '@Url.Action("CreateAssignment", "Professor")',
        dataType: 'json',
        data: {
          subject: '@ViewData["subject"]',
          num: Number('@ViewData["num"]'),
          season: '@ViewData["season"]',
          year: Number('@ViewData["year"]'),
          category: '@ViewData["cat"]',
          asgname: asgName,
          asgpoints: asgPoints,
          asgdue: asgDue,
          asgcontents: asgContents},
        success: function (data, status) {
          //alert(JSON.stringify(data));
          if (!data.success) {
            alert("Unable to add assignment");
          }
          location.reload();
        },
          error: function (ex) {
              alert("CreateAssignment controller did not return successfully");
        }
        });

    }

    function LoadData() {
      classname.innerText = '@ViewData["subject"] @ViewData["num"] @ViewData["season"] @ViewData["year"]';

      var tbl = document.getElementById("tblAssignments");
      var body = tbl.getElementsByTagName("tbody")[0];
      tbl.removeChild(body);

      $.ajax({
        type: 'POST',
        url: '@Url.Action("GetAssignmentsInCategory", "Professor")',
        dataType: 'json',
        data: {
          subject: '@ViewData["subject"]',
          num: Number('@ViewData["num"]'),
          season: '@ViewData["season"]',
          year: Number('@ViewData["year"]'),
          category: '@ViewData["cat"]'},
        success: function (data, status) {
          //alert(JSON.stringify(data));
          PopulateTable(tbl, data);

        },
          error: function (ex) {
              alert("GetAssignmentsInCategory controller did not return successfully");
        }
        });


    }

  </script>

}

Team91LMS/LMS_handout/LMS/Views/Professor/Grade.cshtml
@{
    ViewData["Title"] = "Grade";
    Layout = "~/Views/Shared/ProfessorLayout.cshtml";
}

<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body {
      font-family: "Lato", sans-serif;
    }

    .sidenav {
      /*width: 130px;
      height: 210px;
      position: fixed;
      z-index: 1;
      top: 80px;
      left: 10px;*/
      width: 130px;
      height: 210px;
      position: fixed;
      left: 0;
      right: 0;
      /*margin-left: auto;
      margin-right: auto;*/
      z-index: 1;
      top: 50px;

      background: #eee;
      overflow-x: hidden;
      padding: 8px 0;
    }

      .sidenav a {
        padding: 6px 8px 6px 16px;
        text-decoration: none;
        font-size: 18px;
        color: #2196F3;
        display: block;
      }

        .sidenav a:hover {
          color: #064579;
        }

    .main {
      margin-left: 140px;
      min-height: 200px;
      padding: 0px 10px;
    }
  </style>
</head>
<body>

  <div class="sidenav">
    <a href='/Professor/Class?subject=@ViewData["subject"]&num=@ViewData["num"]&season=@ViewData["season"]&year=@ViewData["year"]'>Assignments</a>
    <a href='/Professor/Students?subject=@ViewData["subject"]&num=@ViewData["num"]&season=@ViewData["season"]&year=@ViewData["year"]'>Students</a>
    <a href='/Professor/Categories?subject=@ViewData["subject"]&num=@ViewData["num"]&season=@ViewData["season"]&year=@ViewData["year"]'>Assignment Categories</a>
  </div>


  <div class="main">

    <h4>Grade Submission</h4>
    <div id="submissioncontents"></div>
    <hr />
    <div>
      <input type="text" name="Score" id="Score" class="form-control" placeholder="0" required="" />
    </div>

    <div>
      <input class="btn btn-primary" name="submitButton" id="btnSave" value="Submit Score" type="button" onclick="SubmitScore()">
    </div>

  </div>
</body>
</html>





@section Scripts
  {
  <script type="text/javascript">

    LoadData();


    function SubmitScore() {

      var score = Number($("#Score").val());

      $.ajax({
        type: 'POST',
        url: '@Url.Action("GradeSubmission", "Professor")',
        dataType: 'json',

        data: {
          subject: '@ViewData["subject"]',
          num: Number('@ViewData["num"]'),
          season: '@ViewData["season"]',
          year: Number('@ViewData["year"]'),
          category: '@ViewData["cat"]',
          asgname: '@ViewData["aname"]',
          uid: '@ViewData["uid"]',
          score: score},
        success: function (data, status) {
          //alert(JSON.stringify(data));
          if (!data.success) {
            alert("Unable to submit score");
          }
          location.reload();
        },
          error: function (ex) {
              alert("GradeSubmission controller did not return successfully");
        }
        });

    }

    function LoadData() {

      $.ajax({
        type: 'POST',
        url: '@Url.Action("GetSubmissionText", "Common")',
        dataType: 'text',
        data: {
          subject: '@ViewData["subject"]',
          num: Number('@ViewData["num"]'),
          season: '@ViewData["season"]',
          year: Number('@ViewData["year"]'),
          category: '@ViewData["cat"]',
          asgname: '@ViewData["aname"]',
          uid: '@ViewData["uid"]'},
        success: function (data, status) {
          //alert(data);
          

          var submissiondiv = document.getElementById("submissioncontents");
          if (data == "") {
            submissiondiv.innerHTML = "(none)";
          }
          else {
            submissiondiv.innerHTML = data;
          }
          
        },
          error: function (ex) {
              alert("GetSubmissionText controller did not return successfully");
        }
        });
        
    }

  </script>

}

Team91LMS/LMS_handout/LMS/Views/Professor/Index.cshtml
@{
    ViewData["Title"] = "ProfessorHome";
    Layout = "~/Views/Shared/ProfessorLayout.cshtml";
}

<h4 id="ProfessorInfo"></h4>
<h4 id="Department"></h4>

<div class="col-md-12">
  <h4>My Classes</h4>
  <table id="tblClasses" class="table table-bordered table-striped table-responsive table-hover">
    <thead>
      <tr>
        <th align="left" class="productth">Course</th>
        <th align="left" class="productth">Name</th>
        <th align="left" class="productth">Semester</th>
      </tr>
    </thead>
    <tbody></tbody>
  </table>
</div>

@section Scripts
  {
  <script type="text/javascript">

    LoadData();


    function LoadData() {


      $.ajax({
        type: 'POST',
        url: '@Url.Action("GetUser", "Common")',
        dataType: 'json',
        data: { uid: '@User.Identity.Name' },
        success: function (data, status) {

          if (data.success == false) {
            alert("An error occured when loading user's information");
          }
          else {
            ProfessorInfo.innerText = data.fname + " " + data.lname + "    " + data.uid;
            Department.innerText = "Department: " + data.department;
          }
        },
        error: function (ex) {
            alert("GetUser controller did not return successfully");
        }
      });

      var tbl = document.getElementById("tblClasses");
      var body = tbl.getElementsByTagName("tbody")[0];
      tbl.removeChild(body);

      var newBody = document.createElement("tbody");

      $.ajax({
        type: 'POST',
        url: '@Url.Action("GetMyClasses", "Professor")',
        dataType: 'json',
        data: { uid: '@User.Identity.Name' },
        success: function (data, status) {

          //alert(JSON.stringify(data));

          $.each(data, function (i, item) {

            var tr = document.createElement("tr");
            
            var td = document.createElement("td");
            td.appendChild(document.createTextNode(item.subject + item.number));
            tr.appendChild(td);

            var td = document.createElement("td");
            var a = document.createElement("a");
            a.setAttribute("href", "/Professor/Class/?subject=" + item.subject + "&num=" + item.number + "&season=" + item.season + "&year=" + item.year);            
            a.appendChild(document.createTextNode(item.name));
            td.appendChild(a);
            tr.appendChild(td);

            var td = document.createElement("td");
            td.appendChild(document.createTextNode(item.season + " " + item.year ));
            tr.appendChild(td);

            newBody.appendChild(tr);

          });
          tbl.appendChild(newBody);
          
        },
          error: function (ex) {
              alert("GetMyClasses controller did not return successfully");
        }
        });


      return false;
    }



  </script>

}